services:
  - type: worker
    name: binance-render
    env: python
    buildCommand: pip install playwright python-telegram-bot && playwright install --with-deps
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
